name: craft_dots
description: A mobile app to create art work with beads.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  archive: ^4.0.7
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  flutter_colorpicker: ^1.0.1
  sqflite: ^2.0.2+1
  path: ^1.8.1
  esys_flutter_share_plus:
  path_provider: ^2.0.9
  pdf: ^3.11.0
  screenshot: ^3.0.0
  printing: ^5.12.0
  camera: 0.10.0+1
  image_picker: ^0.8.5+3
  image: ^4.1.0
  undo: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
